name: inventra
description: "Inventra — Smart Inventory Management for SMEs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Routing
  go_router: ^17.1.0

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  cloud_functions: ^6.1.0
  firebase_messaging: ^16.1.3
  firebase_storage: ^13.2.0

  # Models / Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

  # Barcode Scanner
  mobile_scanner: ^7.2.0

  # Local Storage
  hive_ce_flutter: ^2.3.4
  hive_ce: ^2.10.0

  # UI
  fl_chart: ^1.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Utilities
  connectivity_plus: ^7.0.0
  uuid: ^4.5.1
  equatable: ^2.0.7
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  build_runner: ^2.13.1
  riverpod_generator: ^4.0.3
  hive_ce_generator: ^1.7.0

  # Testing
  mockito: ^5.4.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
